### ISSUE TITLE
Autostart doesn't work due to invalid path / Missing executeable

### ISSUE THREAD

**Issue by iotku** [jellyfin/jellyfin-windows-tray#8]
**Summary**

When "Autostart" is selected in the menu of the tray an entry is added to `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` linking to `%Temp%\.net\JellyfinTray\l2cxugcr.jn2\JellyfinTray.exe` (in the Temp directory of my current user), however while the folder does exist, `JellyfinTray.exe` **does not exist** in that folder, thus it does not auto-start at logon.

**Troubleshooting performed**
I tried disabling autostart, deleting the folder in the temp directory and then enabling autostart again, and while the folder was regenerated `JellyfinTray.exe` still does not exist in that folder.

**Expected Behavior** 
`JellyfinTray.exe` would exist where the startup entry is pointing and enabling autostart would start Jellyfin Tray/Jellyfin once the user has logged on.

**System Info**
OS: Windows 10
Jellyfin Version: 10.4.2

**Comment by iotku** [comment]
Could possibly be related to https://github.com/jellyfin/jellyfin-windows-tray/issues/1

I used the normal installer for Jellyfin, but it doesn't appear that `HKEY_LOCAL_MACHINE\Software\Jellyfin\Server` exists but rather `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Jellyfin\Server` does (never thought I used the 32bit installer, but ok)

The if statement here:
https://github.com/jellyfin/jellyfin-windows-tray/blob/master/Program.cs#L136

Looks pretty suspicious and possibly lacking {} brackets, but I'm not familiar with C#

**Comment by anthonylavado** [comment]
I think we spoke about this on chat a while ago. I have a better handle on what's going on now.

For posterity, I'll write out what we spoke about.
The brackets missing are fine - what C# will do is execute the next statement that follows. So it executes the next line.

What's happening is that sometimes, the .NET Self-Contained Executable sometimes goes missing. So this little utility was written in .NET Core 3.0, while Jellyfin was running on .NET 2.1. As a result I had to choose a deployment type that would include the runtime files, since I couldn't share the ones that were part of Jellyfin. When the tray application is launched for the first time, it searches that temp folder for it's extracted contents, and starts from there. If it can't find them for some reason, then it will fail to launch. This is in the startup mode, so it's before any of the main program gets a chance to run - otherwise I would catch the error and do something about it.

Now that Jellyfin has moved over to .NET Core 3.1, I'll be able to update this app and share the runtime files. This means that it shouldn't disappear on you :-)
